### ISSUE TITLE
A training bug in network_exp_msg_chn.py?

### ISSUE THREAD

**Issue by yunhan-zhao** [anglixjtu/msg_chn_wacv20#2]
Hi,

Please correct me if I'm wrong. I find that there seems to have a bug in the training code.

Line 137 in `trainers/DepthTrainer.py`, the network takes 3 inputs. However, Line 182 in `workspace/exp_msg_chn/network_exp_msg_chn.py` specifies that the network only takes two arguments as the input. In this case, which C should we use? Shall we use C from input or C computed in Line 183?

Thanks

**Comment by anglixjtu** [comment]
Hi @yzhao520, thank you for pointing out this bug for me. The msg_chn network just takes 2 arguments as the input. C in Line 183 and C from the dataloader are identical. I just fixed the bug in '''trainers/DepthTrainer.py'''.

**Comment by anglixjtu** [comment]
Hi @yzhao520, thank you for pointing out this bug for me. The msg_chn network just takes two arguments as input. C computed in Line 183 and C from the dataloader are identical. I just fixed the bug in ```trainers/DepthTrainer.py```.

**Comment by yunhan-zhao** [comment]
Thanks for your reply! Closing this issue now.
