### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by USTC-Keyanjie** [anglixjtu/msg_chn_wacv20#4]
Hi,

I want to reproduce the results you achieved, so I downloaded the pre-trained model and run the `run_eval.py`.  When I choose `selval` dataset, I got the results as expected. However, FileNotFoundError happened when I choose `test` dataset.

```
{'train': {85898}, 'val': {6852}, 'selval': {1000}, 'test': {1000}}
< Evaluate mode ! >
loading checkpoint from : ckpt/final_model.pth
Checkpoint was loaded successfully!

Evaluating on [test] set, Epoch [0] ! 

Traceback (most recent call last):
  File "/home/kyj/workspaces/msg_chn/run_eval.py", line 117, in <module>
    net = mytrainer.evaluate()
  File "/home/kyj/workspaces/msg_chn/trainers/DepthTrainer.py", line 219, in evaluate
    for data in self.dataloaders[s]:
  File "/home/kyj/miniconda3/envs/3d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/kyj/miniconda3/envs/3d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/kyj/miniconda3/envs/3d/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/kyj/miniconda3/envs/3d/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/kyj/miniconda3/envs/3d/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/kyj/miniconda3/envs/3d/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/kyj/workspaces/msg_chn/dataloader/KittiDepthDataset.py", line 103, in __getitem__
    rgb = Image.open(rgb_path)
  File "/home/kyj/miniconda3/envs/3d/lib/python3.6/site-packages/PIL/Image.py", line 2766, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '//data/public_dataset/kitti/depth/depth_selection/test_depth_completion_anonymous/image/00000000.png'


Process finished with exit code 1
```
I try to debug this problem, the length of the file name should be 10 numbers but just 8 numbers in the code.

I locate the problem in this place of code:

```
        elif self.setname == 'test':
            data_path = str(self.data[item])
            idx = data_path.find('velodyne_raw')
            fname = data_path[idx + 12:]
            idx2 = fname.find('test')
            rgb_path = data_path[:idx] + 'image/' + fname[idx2 + 4:]
            rgb = Image.open(rgb_path)
```

The value of `self.data[item]` is '//data/public_dataset/kitti/depth/depth_selection/test_depth_completion_anonymous/velodyne_raw/0000000000.png', `fname` will be '/0000000000.png', so the `idx2` must be -1. Maybe the problem is my data storage format.

Please help me fix this problem.

Besides, I have an another question: Kitti have not provided the ground truth of 'test_depth_completion_anonymous', why can you compute the these error metrics in test dataset?

Best regards,
Yanjie Ke

**Comment by anglixjtu** [comment]
Hi @USTC-Keyanjie, there is no problem with your data storage format. I wrongly updated a problematic code. You can fix the problem by simply eliminating the index after ```fname```, like ```rgb_path = data_path[:idx] + 'image/' + fname```. We also modified  Line 103-104 in ```dataloader/KittiDepthDataset.py ``` in our source code. Thank you for letting us know about this issue!

Regarding the test scores, I can't compute error metrics by myself. I uploaded our results to KITTI website to see the performance.

**Comment by USTC-Keyanjie** [comment]
Thank you for your reply!

I have tried the solution you provided. Actually, I can run the code normally now, but the results is terrible.

```
{'train': {85898}, 'val': {6852}, 'selval': {1000}, 'test': {1000}}
< Evaluate mode ! >
loading checkpoint from : ckpt/final_model.pth
Checkpoint was loaded successfully!

Evaluating on [test] set, Epoch [0] ! 

Evaluation results on [test]:
=============================
[Loss]: 8.33524182
[MAE()]: 533.38406484
[RMSE()]: 2609.69747200
[iMAE()]: 2.46884217
[iRMSE()]: 10.29747871
[Time]: 0.0072
[Time_av]: 0.0548

```
I guess it is caused by the input and gt not matching, the reason is being checked.

**Comment by anglixjtu** [comment]
Yes, @USTC-Keyanjie. Actually the code can not be used to evaluate the performance on the test set, since we do not have ground truth. So the scores are meaningless in test mode.

**Comment by USTC-Keyanjie** [comment]
Got it! Thank you for your patience and this great work!
