### ISSUE TITLE
Unable to reproduce results

### ISSUE THREAD

**Issue by USTC-Keyanjie** [anglixjtu/msg_chn_wacv20#6]
Hi, I want to reproduce the results but failed. Actually, the result I got is very close to what you provided.
```
{'train': {85898}, 'val': {6852}, 'selval': {1000}, 'test': {1000}}
< Evaluate mode ! >
loading checkpoint from : workspace/exp_msg_chn/checkpoints/DataParallel_ep0050.pth.tar
Checkpoint was loaded successfully!

Evaluating on [val] set, Epoch [0] !

Evaluation results on [val]:
=============================
[Loss]: 0.73175457
[MAE()]: 227.63107457
[RMSE()]: 824.13766775
[iMAE()]: 0.97879498
[iRMSE()]: 2.42858775
[Time]: 0.0071
[Time_av]: 0.0164

```

RMSE is higher than the result you provided. 

**I want to ask**
Have you pre-trained on other data sets (such as virtual kitti)?
I noticed that there is a `blind` option in `param.json`, have you opened it?
Can you share how many graphics cards you used to achieve the best results? I suspect that my multi-graphics training strategy caused the inaccuracy in the results.

**what i change**:

*train.py*
```
line 37
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
changed to
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1,2,3,4,5,6"

line 66
params['gpu_id'] = "0"
changed to
params['gpu_id'] = "0,1,2,3,4,5,6"
```

My environment information:

```
os: Ubuntu 18.04.3 LTS
cuda: release 10.1, V10.1.243
cudnn: 7603
pytorch: 1.5
Graphics: GeForce RTX 2080 Ti * 8
```

**Comment by anglixjtu** [comment]
Hi @USTC-Keyanjie, I haven't pre-trained on other data sets. And I did not open ```blind``` option.
I used two graphics cards to train the model.  It seems that there is no problem with your multi-graphics training strategy.
Also, based on some experience with training other CNN networks, using more graphics cards and increasing the batch size is likely to improve results. You can try to train with different batch sizes. 

However, I notice that your RMSE is only 3mm higher than mine. The difference is small. I'm guessing that training 50 epochs doesn't get the best model. Maybe you can first test the intermediate models obtained by training with different epochs (for example, 20 epochs, 30 epochs, 40 epochs).

**Comment by USTC-Keyanjie** [comment]
Thank you for your reply! The difference is very very small indeed. I will try your training strategy again!

Thank you again for this great work!
